# Check branch for linting problems
name: Linters
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Deps
        run: |
          bun install
          cp .env.example .env
      - name: Svelte-Check
        run: bun run check
      - name: ESLint
        run: bun run eslint .
